# Generated by Django 5.1.3 on 2025-01-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='especialidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
