# Generated by Django 5.1.3 on 2025-01-18 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='rest_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercises',
        ),
        migrations.AddField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(to='app.exercise'),
        ),
    ]
