# Generated by Django 5.1.3 on 2025-01-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_training_rest_time_remove_training_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='rest_time',
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest_time',
            field=models.IntegerField(default=90),
        ),
    ]
