# Generated by Django 5.1.3 on 2025-01-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_training_rest_time_exercise_rest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='rest_time',
            field=models.IntegerField(default=90, verbose_name='Tempo de Descanso'),
        ),
    ]
