# Generated by Django 5.1.3 on 2025-01-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_training_exercises_trainingexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='exercises',
            field=models.ManyToManyField(to='app.exercise'),
        ),
        migrations.DeleteModel(
            name='TrainingExercise',
        ),
    ]
