# Generated by Django 5.1.3 on 2025-01-18 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_training_exercises_delete_trainingexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='rest_time',
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercises',
        ),
        migrations.CreateModel(
            name='FichaDeTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.IntegerField(default=12, verbose_name='Número de Repetições')),
                ('rest_time', models.IntegerField(default=90, verbose_name='Tempo de Descanso (segundos)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.exercise', verbose_name='Exercício')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.training', verbose_name='Treino')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='ficha_de_treino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='app.fichadetreino', verbose_name='Ficha de Treino'),
            preserve_default=False,
        ),
    ]
