# Generated by Django 5.1.3 on 2025-01-18 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_training_ficha_de_treino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichadetreino',
            name='rest_time',
        ),
    ]
