# Generated by Django 5.1.3 on 2025-01-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_fichadetreino_rest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='rest_time',
            field=models.IntegerField(default=90, verbose_name='Tempo de Descanso (segundos)'),
        ),
        migrations.DeleteModel(
            name='FichaDeTreino',
        ),
    ]
