# Generated by Django 5.1.3 on 2025-01-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_training_rest_time_fichadetreino'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='rest_time',
            field=models.IntegerField(default=90, verbose_name='Tempo de Descanso (segundos)'),
        ),
    ]
