# Generated by Django 5.1.3 on 2025-01-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_training_rest_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FichaDeTreino',
            new_name='TrainingSheet',
        ),
    ]
