# Generated by Django 5.1.3 on 2025-01-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_fichadetreino_trainingsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsheet',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome da Ficha de Treino'),
            preserve_default=False,
        ),
    ]
