# Generated by Django 5.1.3 on 2025-01-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_trainingsheet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsheet',
            name='name',
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Nome do Treino'),
            preserve_default=False,
        ),
    ]
