# Generated by Django 5.1.3 on 2025-01-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_trainingsheet_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Frequência', 'verbose_name_plural': 'Frequências'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercício'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Treinamento', 'verbose_name_plural': 'TreinamentoS'},
        ),
        migrations.AlterModelOptions(
            name='trainingsheet',
            options={'verbose_name': 'Ficha de Treino', 'verbose_name_plural': 'Fichas de Treino'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
