# Generated by Django 5.1.3 on 2025-01-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_attendance_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
    ]
